backend = "glx"

corner-radius = 15

blur:
{
  method = "dual_kawase";
  size = 10;
  strength = 3;
};

blur-background = true
blur-background-fixed = true

rules = (
  { 
    match = "class_g = 'dwm' || class_g = 'dmenu' || class_g = 'Dunst'"; 
    corner-radius = 0; 
  },

	{ match = "focused"; opacity = 0.92; },
	{ match = "!focused"; opacity = 0.85; },
	{ match = "popup_menu"; opacity = 0.9; },
	{ match = "dropdown_menu"; opacity = 0.9; },
)
